### ISSUE TITLE
Error: jwt is not defined

### ISSUE THREAD

**Issue by Splinteer** [auth0/auth0-spa-js#1086]
When trying to use auth0 with my angular app I got this error when dealing with handleRedirectCallback().
```
Error: jwt is not defined
    at auth0-spa-js.production.esm.js:1:31086
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
    at new ZoneAwarePromise (zone.js:1429:21)
    at asyncToGenerator.js:21:1
    at te.handleRedirectCallback (auth0-spa-js.production.esm.js:1:30565)
    at app.component.ts:27:22
    at Generator.next (<anonymous>)
    at resolvePromise (zone.js:1211:31)
    at zone.js:1118:17
    at zone.js:1134:33
    at asyncGeneratorStep (asyncToGenerator.js:6:1)
    at _throw (asyncToGenerator.js:29:1)
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26274:33)
    at _ZoneDelegate.invoke (zone.js:371:52)
    at Zone.run (zone.js:134:43)
    at zone.js:1275:36
```

Here is my code:
```
import { Component } from '@angular/core';
import { Auth0Client, createAuth0Client } from '@auth0/auth0-spa-js';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'app-root',
  // templateUrl: './app.component.html',
  template: ` <button (click)="login()" *ngIf="auth0">Login</button>`,
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'front';

  public auth0?: Auth0Client;

  constructor() {
    this.getAuth();
  }

  async getAuth() {
    this.auth0 = await createAuth0Client({
      domain: environment.auth0.domain,
      clientId: environment.auth0.clientId,
      cacheLocation: 'localstorage',
    });

    await this.auth0.handleRedirectCallback();

    const user = await this.auth0.getUser();
    console.log(user);
  }

  login() {
    (<Auth0Client>this.auth0).loginWithRedirect({
      authorizationParams: {
        redirect_uri: 'http://localhost:4200/',
      },
    });
  }
}
```

I made a brand new project with only that component in. I also tried with the auth0-angular package before but got the exact same error. I also tried to install jsonwebtoken package but it's not working too.

How to fix this error ?

I have followed both guides with the same error:
https://auth0.com/docs/libraries/auth0-single-page-app-sdk#use-rotating-refresh-tokens
https://auth0.com/docs/quickstart/spa/angular/01-login

**Comment by frederikprijck** [comment]
Thanks for reaching out. Based on the provided information, it's hard to tell what's going on.

Can you reproduce it using our official sample https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01 ? If you can, could you elaborate on the steps to take to reproduce it?

**Comment by frederikprijck** [comment]
Closing because no activity.
