### ISSUE TITLE
Angular CLI Optimized Build Invalid state 

### ISSUE THREAD

**Issue by adstep** [auth0/auth0-spa-js#199]
Angular CLI: 8.3.2
Node: v10.16.3

Follow the instructions in the [Angular:Login](https://auth0.com/docs/quickstart/spa/angular2/01-login) documentation.

Serve the site with optimization turned on.

```
main.c651bd17c166de67a914.js:1 ERROR Error: Invalid state
    at t.<anonymous> (main.c651bd17c166de67a914.js:1) [angular]
    at :4200/main.c651bd17c166de67a914.js:1:93512 [angular]
    at Object.next (main.c651bd17c166de67a914.js:1) [angular]
    at :4200/main.c651bd17c166de67a914.js:1:92555 [angular]
    at new ZoneAwarePromise (polyfills.acbc03ba9e6edf45a57e.js:1) [angular]
    at r (main.c651bd17c166de67a914.js:1) [angular]
    at t.handleRedirectCallback (main.c651bd17c166de67a914.js:1) [angular]
    at mergeMap_MergeMapSubscriber.project (main.c651bd17c166de67a914.js:1) [angular]
    at mergeMap_MergeMapSubscriber._tryNext (main.c651bd17c166de67a914.js:1) [angular]
    at mergeMap_MergeMapSubscriber._next (main.c651bd17c166de67a914.js:1) [angular]
    at mergeMap_MergeMapSubscriber.next (main.c651bd17c166de67a914.js:1) [angular]
    at catchError_CatchSubscriber._next (main.c651bd17c166de67a914.js:1) [angular]
    at catchError_CatchSubscriber.next (main.c651bd17c166de67a914.js:1) [angular]
    at ReplaySubject_ReplaySubject._subscribe (main.c651bd17c166de67a914.js:1) [angular]
```

There appears to be some issue with ```auth0-spa-js.production.js```. If I use ```auth0-spa-js-development.js``` I get no errors.

**Comment by adstep** [comment]
Dupe of #182. Looks like a fix is in the works.
